const noticeData = [
    {
        "id":0,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":1,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE , MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":2,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":3,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":4,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":5,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":6,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":7,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
    {
        "id":8,
        "notice":"POSTMATRIC SCHOLARSHIP TIME-TABLE (2023-24) FOR GENERAL,MINORITY AND OBC CATEGORY 08 JULY 2024"
    },
]
export default noticeData;